apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobId }}
  labels:
    pertaas-job: "true"
spec:
  template:
    metadata:
      name: {{ .Values.jobId }}
      labels:
        pertaas-job: "true"
    spec:
      containers:
        - name: job
          image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/pertaas-{{ .Values.jobId }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
          envFrom:
            - secretRef:
                name: couchbase-secret
          env:
            - name: JOB_ID
              value: {{ .Values.jobId }}
            - name: STEP_DURATION
              value: {{ quote .Values.stepDuration }}
            - name: REQUEST_JSON
              value: |
                {{ .Files.Get (printf "%s" .Values.fileName) }}
          resources:
            requests:
              cpu: {{ quote .Values.cpu }}
              memory: {{ quote .Values.ram }}
            limits:
              cpu: {{ quote .Values.cpu }}
              memory: {{ quote .Values.ram }}
      restartPolicy: Never
